### ISSUE TITLE
[11288] Failed to execute script LumberSnake (HyperAPI)

### ISSUE THREAD

**Issue by andypick** [thechosentom/LumberSnake#11]
Using the latest Lumbersnake.exe extracts the logs from a zip fine and creates the log dump folder but when creating the hyper file generates the following errors - 

Traceback (most recent call last):
  File "LumberSnake (HyperAPI).py", line 314, in <module>
  File "LumberSnake (HyperAPI).py", line 95, in HyperCreate
  File "site-packages\tableauhyperapi\hyperprocess.py", line 102, in __init__
  File "site-packages\tableauhyperapi\impl\dllutil.py", line 118, in check
tableauhyperapi.hyperexception.HyperException: HYPER:generic: IPC_NamedPipe::Select(WaitForMultipleObjects): Timeout
[11288] Failed to execute script LumberSnake (HyperAPI)

no hyper file is then generated.

Thanks for any help

**Comment by ddvmanju** [comment]
Hi All,

I am also getting the above issue.
Appreciate if any one help as i got stuck this issue from long time.

Thanks
