### ISSUE TITLE
ImportError: No module named filedialog

### ISSUE THREAD

**Issue by vamsisasee** [thechosentom/LumberSnake#3]
Traceback (most recent call last):
  File "E:\LumberSnake\LumberSnake (2018.1.1).py", line 19, in <module>
    from Tkinter.filedialog import askopenfilename
ImportError: No module named filedialog

![image](https://user-images.githubusercontent.com/14211621/45684248-578fd300-bb63-11e8-86cb-4fae09bdd060.png)

**Comment by vamsisasee** [comment]
The issue seems to be with the python version. In 2.7 import the module tkinter.filedialog as **tkFileDialog**

You can fix this issue by editing the file LumberSnake (2018.1.1).py line #19 as below


![image](https://user-images.githubusercontent.com/14211621/45684399-cff69400-bb63-11e8-96ef-f94e1b939448.png)


After fixing this, you may end up with the error **IndexError: list index out of range**

Begin Processing ...
Checking Log Dump for files ...
Cleaning all files in filepath .\Log Dump\
worker1.zip
worker2.zip
failed on tabadminservice/inprogress_remote_logs.zip
[Errno 2] No such file or directory: './Log Dump/tabadminservice/inprogress_remo
te_logs.zip'
Successfully extracted worker1.zip!
Successfully extracted worker2.zip!
.\Log Dump\worker1.zip has no data!
.\Log Dump\worker2.zip has no data!
qp-batch processed ...
Traceback (most recent call last):
  File "LumberSnake20181.py", line 204, in <module>
  File "LumberSnake20181.py", line 122, in get_merged
IndexError: list index out of range
[11628] Failed to execute script LumberSnake20181

**Comment by thechosentom** [comment]
Fixed in the most recent version, please use Python 3.7.3 moving forward.

**Comment by CutterW** [comment]
Traceback (most recent call last):
  File "C:/Users/JITBDGROUP/Desktop/python program/Text Editor.py", line 2, in <module>
    import filedialog as tf
ModuleNotFoundError: No module named 'filedialog'
>>> import sys
>>> print(sys.version)
3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)]
>>> print(sys.executable)
C:\Users\JITBDGROUP\AppData\Local\Programs\Python\Python38-32\pythonw.exe
>>> import filedialog
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    import filedialog
ModuleNotFoundError: No module named 'filedialog'
>>> import FileDialog
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    import FileDialog
ModuleNotFoundError: No module named 'FileDialog'
>>>

**Comment by irik77587** [comment]
```
Traceback (most recent call last):
  File "C:/Users/JITBDGROUP/Desktop/python program/Text Editor.py", line 2, in <module>
    import filedialog as tf
ModuleNotFoundError: No module named 'filedialog'
>>> import sys
>>> print(sys.version)
3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)]
>>> print(sys.executable)
C:\Users\JITBDGROUP\AppData\Local\Programs\Python\Python38-32\pythonw.exe
>>> import filedialog
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    import filedialog
ModuleNotFoundError: No module named 'filedialog'
>>> import FileDialog
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    import FileDialog
ModuleNotFoundError: No module named 'FileDialog'
>>>
```
